todo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.TodoListView.as_view(), name="todo_list"),
    path("new/", views.TodoCreateView.as_view(), name="todo_create"),
    path("do/<int:pk>/delete/", views.TodoDeletView.as_view(), name="todo_delete"),
]

todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path("", include("todo.urls")),
]

todo/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse


class Todo(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField(blank=True, null=True)

    PRIORITY = (
        (1, "High"),
        (2, "Medium"),
        (3, "Low"),
    )
    priority = models.PositiveSmallIntegerField(choices=PRIORITY, default=3)
    date = models.DateField(default=timezone.now)
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = "date", "priority",
        
    def get_absolute_url(self):
        return reverse("todo_list")

todo/views.py
from django.urls import reverse
from .models import Todo
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.detail import DetailView


class TodoListView(ListView):
    model = Todo


class TodoCreateView(CreateView):
    model = Todo
    fields = "__all__"
    template_name = "todo/todo_list.html"


class TodoDeletView(DeleteView):
    model = Todo

    def get_success_url(self):
        return reverse("todo_list")

todo/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}Todo App{% endblock title %}</title>
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	</head>
	<body>
		{% block content %}
		{% endblock content %}
		<script src="{% static 'js/jquery-3.3.1.js' %}"></script>
		<script src="{% static 'js/popper.js'%}"></script>
	</body>
</html>

todo/templates/todo/todo_list.html
{% extends "todo/base.html" %}

{% block title %} List of Todos {% endblock title %}

{% block content %}
	
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				{% for todo in todo_list %}
					<div>
						<h3>{{todo.title}}</h3>
						<form action="{% url 'todo_delete' todo.pk %}" method="post">
							{% csrf_token %}
							<input type="submit" value="Done">
						</form>
						<small>For Date:
							{% now "M. d, Y" as todays_date %}
							{% if todo.date|date:"M. d, Y" == todays_date %}
								Today
							{% else %}
								{{todo.date}}
							{% endif %}
						</small><br>
						<small><strong>Priority : {{todo.get_priority_display}}</strong></small>
						<section>{{todo.description}}</section>
					</div>
					<hr>
				{% empty %}
					<h1>Nothing to do.</h1>
				{% endfor %}
			</div>
			
			<div class="col-md-4">
				<form action="{% url 'todo_create' %}" method="post">
					{% csrf_token %}
					<table>
						<tr><th>
							<label for="id_title">Title:</label></th><td>
							<input type="text" name="title" maxlength="150" required id="id_title"></td></tr>
						<tr><th>
							<label for="id_description">Description:</label></th><td>
							<textarea name="description" cols="40" rows="10" id="id_description"></textarea></td></tr>
						<tr><th>
							<label for="id_priority">Priority:</label></th><td><select name="priority" id="id_priority">
								<option value="1">High</option>
		
								<option value="2">Medium</option>
		
								<option value="3" selected>Low</option>
		
								</select>
						</td></tr>
						<tr><th>
							<label for="id_date">Date:</label>
						</th><td>
						<input type="text" name="date" value="2018-11-03" required id="id_date">
						<input type="hidden" name="initial-date" value="2018-11-03 12:46:47" id="initial-id_date"></td></tr>
					</table>
						<input type="submit" value="Submit">
				</form>
			</div>
		</div>
		
	</div>
		
		<div class="split right">
		  <div class="centered">
		    
		  </div>
	</div>
{% endblock content %}